stages:
  - deploy

deploy_to_server:
  stage: deploy
  only:
    - main
  script:
    # 1. Download the secure files (fetches your `gitlab_ci_deploy_key`).
    - curl --silent "https://gitlab.com/gitlab-org/incubation-engineering/mobile-devops/download-secure-files/-/raw/main/installer" | bash

    # 2. Move the private key to a known location and secure permissions.
    - mv .secure_files/gitlab_ci_deploy_key ssh_deploy_key
    - chmod 600 ssh_deploy_key

    # 3 connect in one line
    - ssh -o "StrictHostKeyChecking=no" -o "UserKnownHostsFile=/dev/null" -i ssh_deploy_key startup-week@90.103.29.148 -p 5225 "echo 'SSH connection successful to startup-week!'"
    - cd web
    - git pull https://linventif:$pull_token@gitlab.com/univlille/startupweek/2025/groupe-7/web.git
    - yarn install
    - yarn run build
    - yarn run prod
