stages:
    - deploy

deploy_to_server:
    stage: deploy
    only:
        - main
    script:
        # 1. Download the secure files (fetches your `gitlab_ci_deploy_key`).
        - curl --silent "https://gitlab.com/gitlab-org/incubation-engineering/mobile-devops/download-secure-files/-/raw/main/installer" | bash

        # 2. Move the private key to a known location and secure permissions.
        - mv .secure_files/gitlab_ci_deploy_key id_rsa
        - chmod 600 id_rsa

        # 3. SSH into remote server and run the deployment steps there.
        - ssh -o "StrictHostKeyChecking=no" -o "UserKnownHostsFile=/dev/null" -i id_rsa startup-week@90.103.29.148 -p 5225 << 'EOF'
          echo "SSH connection successful to startup-week!"
          cd web
          git pull
          npm install
          npm run build
          npm run start
          EOF
